exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
  - css
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules

markdown: kramdown
permalink: /project/:name

sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Tisch合同会社
url: https://www.tisch.llc
plugins:
  - jekyll-sitemap
  - kramdown

google_auto_adsense: ca-pub-2355534368422626