exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor

markdown: kramdown
permalink: /project/:name

sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Tisch合同会社
url: https://www.tisch.llc
plugins:
  - jekyll-sitemap
  - kramdown